### ISSUE TITLE
Update ang3/php-odoo-api-client to ^7.0

### ISSUE THREAD

**Issue by bastien-wink** [Ang3/odoo-bundle#2]
We need this project to run with PHP 8, the only wall left is php-odoo-api-client.
I will create a PR

**Comment by webspin** [comment]
@bastien-wink Did you ever find a resolution? Seems the author is inactive...

**Comment by bastien-wink** [comment]
Indeed, I ended up forking to speed up this PR https://github.com/Ang3/odoo-bundle/pull/3
